36 configure build system and dependencies using nix
tiiuae/vmd pull request #42
Opened 2023-05-08 07:28 UTC by juliuskoskela

https://github.com/tiiuae/vmd/issues/36

2023-05-08 07:37 UTC, juliuskoskela commented
A note about the generated bindings. Apparently a `flake.nix` uses Git to see what source files should be included in the project. Thus generated API bindings have to be committed to the repository.

2023-05-08 08:03 UTC, vadika approved these changes
Looks good to me, except one thing -- may be it's good idea to squash five commits to one.

2023-05-08 10:15 UTC, juliuskoskela commented
> Looks good to me, except one thing -- may be it's good idea to squash five commits to one.

I will squash the whole PR once it's approved.

2023-05-08 10:25 UTC, juliuskoskela commented
Seems that `nix shell` command doesn't work. It doesn't give any error, but also doesn't load the developer shell.

2023-05-08 11:10 UTC, juliuskoskela commented
> Seems that `nix shell` command doesn't work. It doesn't give any error, but also doesn't load the developer shell.

I misunderstood how the `nix shell` command should work. I guess it doesn't open the shell, just takes in a command to execute in it.

2023-05-08 11:14 UTC, juliuskoskela commented
Generated API bindings are included in source control now. As far as I understand, nix requires the sources to be in Git's source control or at least I couldn't get the project to build otherwise.

2023-05-09 20:05 UTC, mikatammi requested changes
I think the flake in general could be made much simpler. I was also thinking do we need or want to use crane to build the actual final package, however I can see the usefulness of using it for the development purposes

This is not all, I just briefly checked some of the Nix changes first. Otherwise a good start

I'd like to have this pattern which matches the nixpkgs repo, where the vmd has a separate nix-file (eg. vmd.nix), which could then be called through the callPackage-function. That ensures the overlays will get used when integrating this into ghaf.

2023-05-09 20:05 UTC, mikatammi commented on flake.lock
> +    "flake-utils_2": {
Please get rid of this _2

2023-05-09 20:05 UTC, mikatammi commented on flake.lock
> +    "systems_2": {
and this

2023-05-09 20:05 UTC, mikatammi commented on flake.nix
> +		inputs.nixpkgs.follows = "nixpkgs";
You can get rid of the _2's above by adding here `inputs.flake-utils.follows = "flake-utils";`

2023-05-09 20:05 UTC, mikatammi commented on flake.nix
> +
A hint, you could add formatter here to automatically prettify your nix files in this project, just like in ghaf:

https://github.com/tiiuae/ghaf/blob/main/flake.nix#L60

Then you could run `nix fmt *` to format your files

2023-05-09 20:07 UTC, mikatammi commented
> Generated API bindings are included in source control now. As far as I understand, nix requires the sources to be in Git's source control or at least I couldn't get the project to build otherwise.

You could also generate the bindings inside the derivation. We can have a deeper look at this

2023-05-10 12:16 UTC, juliuskoskela commented on flake.nix
> +		inputs.nixpkgs.follows = "nixpkgs";
Resolved in https://github.com/tiiuae/vmd/pull/42/commits/94f68ae6ca8b9552aada4402c3cf285e55499fa2

2023-05-10 12:19 UTC, juliuskoskela commented on flake.nix
> +
Resolved in https://github.com/tiiuae/vmd/pull/42/commits/e309c277f1aa5a300be515c881c88eb5844eab28

2023-05-10 13:12 UTC, juliuskoskela commented
> I think the flake in general could be made much simpler. I was also thinking do we need or want to use crane to build the actual final package, however I can see the usefulness of using it for the development purposes
> 
> This is not all, I just briefly checked some of the Nix changes first. Otherwise a good start
> 
> I'd like to have this pattern which matches the nixpkgs repo, where the vmd has a separate nix-file (eg. vmd.nix), which could then be called through the callPackage-function. That ensures the overlays will get used when integrating this into ghaf.

One thing to note is that `vmd` is ultimately 3 different programs. There will be the server, client-cli and client-gui.

The way I see it is that the clients are obviously just normal packages that would be installed on any normal system through a package manager. The server on the other hand is different. It's a (system?) service which would be configured and enabled in the configuration on the host machine. It will run in `admin-vm` or something similar and the traffic will be routed from `netvm` (the single point of outside network traffic).

If the routing is going to happen just with local network as in `<IP>:<PORT> -> netvm -> localhost:<PORT> -> admin-vm(vmd)` (this might happen with shared memory or some other mechanism, as far as I know the design on iter-vm communication isn't finished yet), the configuration regarding `vmd` would span several modules (such as `netvm`) in the Ghaf system. Furthermore it would seem  that `vmd` should be configured as a [nixOS module](https://scvalex.net/posts/58/). Probably configuration of `vmd` would be part of the configuration of `admin-vm` if that will be the context we settle on (or are they actually the same thing?).

Here's a rough sketch on how a part of the configuration could look like:

```nix
{
  netvm = { config, pkgs, ... }: {
    routing.vmd = {
      inbound-port = 1234;
      outbound-port = 6666; # localhost:6666
    };
    #...
  };
  
  adminvm = { config, pkgs, ... }: {
    services.vmd = {
      enable = true;
      package = pkgs.vmd;
      port = 6666;
    };
  };
  
  #...
}
```

In summary:

- We have two packages `vmd-client-cli` and `vmd-client-gui` which would be distributed as normal package derivations and are intended to be used on a "client" machine.
- We have a [module](https://nixos.wiki/wiki/NixOS_modules) which defines `vmd-server`. This service would be enabled and configured as a part of the host configuration of Ghaf.

2023-05-11 07:20 UTC, vilvo commented
> 
> One thing to note is that `vmd` is ultimately 3 different programs. There will be the server, client-cli and client-gui.
> 
> _Maybe this is an argument to separate vmd-server and vmd-client(s) into separate repositories as originally planned? It seems they are very separate concerns from the perspective of building the Ghaf-system._

I think this is a bit misrepresentation of dependency between the `vmd-server` and `client-*`. `vmd-server` as such with no `client-*` is practically of no use. One could argue that `vmd-server` can have scripted tests but in essence those would just duplicate the `client-cli` which should also work as reference implementation on `vmd-server' client use. Given that, separating repositories sounds not not only bikeshedding but also ignores the depedency between the server and the client. Sure, design removes tight coupling between the server and the client but the dependency is there. 
 
At early stages of development where we can see also the generated bindings changing with implementation and further added functionality, it's clearer to change both server and the client at the same time. Option is separate repository and disciplined versioning to meet the dependency requirement management but I do not see the point.

This does not rule out separation of server and client(s) to separate repositories in the future - in fact, I've proposed we can do with git subtree split. Still, I do not support it *right now* as the packaging can be managing with respective nix-files and flake targets as was proposed.
 
> The way I see it is that the clients are obviously just normal packages that would be installed on any normal system through a package manager. The server on the other hand is different. It's a (system?) service which would be configured and enabled in the configuration on the host machine. It will run in `admin-vm` or something similar and the traffic will be routed from `netvm` (the single point of outside network traffic).

Yes and no. client-cli should go hand-in-hand with server integration in debug-builds but it could also be installed on other VMs to test routing...

> If the routing is going to happen just with local network as in `<IP>:<PORT> -> netvm -> localhost:<PORT> -> admin-vm(vmd)` (this might happen with shared memory or some other mechanism, as far as I know the design on inter-vm communication isn't finished yet), the configuration regarding `vmd` would span several modules (such as `netvm`) in the Ghaf system. Furthermore it would seem that `vmd` should be defines as a [nixOS module](https://scvalex.net/posts/58/). Probably configuration of `vmd` would be part of the configuration of `admin-vm` if that will be the context we settle on (or are they actually the same thing?).

... which means that client-cli should be possible to install as a package but also should be server dependency for now.
 
If we absolutely insist on separate repositories, I'd like to hear solid arguments on how it handles and solves problems at this point.

2023-05-11 09:12 UTC, juliuskoskela commented
> If we absolutely insist on separate repositories, I'd like to hear solid arguments on how it handles and solves problems at this point.

I don't think separate repositories are a must at this point.

> ... which means that client-cli should be possible to install as a package but also should be server dependency for now.

Aren't both kind of possible by default if the client(s) are just packages?

2023-05-11 09:13 UTC, juliuskoskela commented
> > Generated API bindings are included in source control now. As far as I understand, nix requires the sources to be in Git's source control or at least I couldn't get the project to build otherwise.
> 
> You could also generate the bindings inside the derivation. We can have a deeper look at this

I'd like to figure this one out before merging.

2023-05-11 09:39 UTC, vilvo commented
> > ... which means that client-cli should be possible to install as a package but also should be server dependency for now.
> 
> Aren't both kind of possible by default if the client(s) are just packages?

yes

2023-06-08 13:38 UTC, juliuskoskela commented
Resolved in https://github.com/tiiuae/vmd/pull/40

2023-06-08 13:38 UTC, closed without merging