Test certificates, repository structure and build system
tiiuae/vmd pull request #8
Opened 2023-03-01 22:20 UTC by juliuskoskela

# Repository structure

Repository is split to:

- auth: Create test certs for mutual TLS
- vmd-common: Types that are shared between server and client crates
- vmd-server: Server crate
- vmd-client: GUI-client crate

# Build system

- `cargo build` at root will build all crates using workspaces
- Root Makefile for convenience

# Certificates

`make -C auth` builds test certificates with openssl using mock data. The certificates are put in `auth/certs`

2023-03-02 09:55 UTC, vilvo commented on auth/Makefile
> +VMD_SERVER_KEY=$(DIR)/vmd-server-key.pem
Please rename all these to something like `-sample-` to indicate that they are only for testing. Whoever uses these must be super clear that's the case. Both for server and client.

2023-03-02 09:56 UTC, vilvo commented on auth/Makefile
> +	@echo "Generating vmd-server key and certificate signing request"
The same here - `Generating vmd-server sample/testing key and certificate signing request`

2023-03-02 09:56 UTC, vilvo commented on auth/Makefile
> +	@echo "Generating client key and certificate signing request"
The same here - `Generating vmd-client sample/testing key and certificate signing request`

2023-03-02 09:57 UTC, vilvo commented on vmd-server/Cargo.toml
> +authors = ["Ville Ilvonen <ville.ilvonen@unikie.com>", ]
Add yourself here - you've already bypassed my contributions :-)

2023-03-02 09:59 UTC, juliuskoskela commented
I also think I should alter the repository structure slightly and put the `auth` context in a `tests` folder in root where we can eventually build our tests suite.

2023-03-02 10:01 UTC, vilvo requested changes
In addition to naming the certs with `-sample-` and mentioning it in the generation, please add generated and shared key pairs in the repo for testing purposes for now. Let's not generate the key pairs every time because the key generation will add cargo external dependencies. We could manage those with nix flake eventually but let's do that later.

2023-03-02 10:03 UTC, juliuskoskela commented
> In addition to naming the certs with `-sample-` and mentioning it in the generation, please add generated and shared key pairs in the repo for testing purposes for now. Let's not generate the key pairs every time because the key generation will add cargo external dependencies. We could manage those with nix flake eventually but let's do that later.

I can separate dev dependencies with cargo, but I can take the certs folder out from `.gitignore` and push it with the sample certs for now. I will do that after the other proposed changes.

2023-03-06 11:53 UTC, baz2142 commented on auth/Makefile
> +client: $(CA_CRT)
I'm not sure if it is a good idea to place the clients here, except for possible Rust implementation:
* As we considered before, we might have many clients in many languages, like CLI/Rust, Qt/C++, Web app and so on -- it might be not very convenient to mix different project
* There will be no shared code for server and client
* The only way the server and the client sides will be connected -- RESTapi protocol, which will have different implementation
* It is not the client side's business what is in the server side. We have decoupling. They use a protocol

So I propose to create a different repo for each client. Or, at least, to struct this repo in a more isolated way: move ./Cargo.* files to according directories, because it is implementation-specific. Possible web client implementation will not be needed in Rust, Cargo and so on. Rust project has to contain it inside. JS web app has to contain it's lock files inside, too, not in the root of the repo. Let's not to mix different projects

2023-03-06 11:57 UTC, juliuskoskela commented on auth/Makefile
> +client: $(CA_CRT)
I'm starting to think they should be separate repos. Maybe use `repo` tool to glue them together for tests/ci? That leaves the question of where the API protocol should be though.

2023-03-07 09:35 UTC, baz2142 commented on auth/Makefile
> +client: $(CA_CRT)
We can have 3 repos: vmd for server side, protocol repo and client repo. The protocol repo will be used as submodule to provide both sides needed code

2023-03-07 09:36 UTC, baz2142 commented on auth/Makefile
> +client: $(CA_CRT)
@vilvo, what would you say?

2023-03-07 11:49 UTC, vilvo commented on auth/Makefile
> +client: $(CA_CRT)
Makes sense to separate (decouple) server and client repos. API spec can reside aside server repo as long as it's versioned independently from the server implementation. Separate repo is also an option.
In general - not big fan of submodules. There was just a recent, great article about why not to use submodules so I leave it there https://diziet.dreamwidth.org/14666.html#what-is-wrong-with-git-submodules
My 2 cents for monorepo of server and the API spec.

2023-03-07 11:52 UTC, juliuskoskela commented on auth/Makefile
> +client: $(CA_CRT)
So client in separate repo?

2023-03-07 12:25 UTC, baz2142 commented on auth/Makefile
> +client: $(CA_CRT)
Yeah. Who can create it?

2023-03-07 12:26 UTC, juliuskoskela commented on auth/Makefile
> +client: $(CA_CRT)
Needs privileges from tiiuae I guess. Let's bring it up tomorrow.

2023-03-08 15:12 UTC, vilvo approved these changes

2023-03-08 22:18 UTC, merged